FROM python:3.9.19-alpine3.19

COPY app.py .
COPY templates/index.html /templates/index.html
COPY templates/admin.html /templates/admin.html
COPY templates/login.html /templates/login.html
COPY static/custom.geo.json /static/custom.geo.json
COPY static/logo.png /static/logo.png
COPY requirements.txt .

EXPOSE 5002

RUN pip3 install -r requirements.txt

RUN apk update && apk add bash
RUN apk add emacs

ENTRYPOINT ["python3", "app.py"]
